### ISSUE TITLE
openhab2-flicbutton broken on openhab2 2.5.0 M6

### ISSUE THREAD

**Issue by karidavidsson** [pfink/openhab2-flicbutton#7]
I am using the flic button with openhab2 installation running on Rapsberry PI.
It has been running fine on openhab2 M5, M4 and probably M3 (cant recall exactly when I installed the flic button).
Anyways upgraded the rpi couple of days ago and now the openhab2-flicbutton module does not initialize:

`2019-12-04 22:37:45.007 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler@257015': bundleContext
java.lang.NoSuchFieldError: bundleContext
	at org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler.initButtonDiscoveryService(FlicDaemonBridgeHandler.java:87) ~[?:?]
	at org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler.initialize(FlicDaemonBridgeHandler.java:70) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-12-04 22:37:45.083 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'flicbutton:flicd-bridge:vinaminni': bundleContext
java.lang.NoSuchFieldError: bundleContext
	at org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler.initButtonDiscoveryService(FlicDaemonBridgeHandler.java:87) ~[?:?]
	at org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler.initialize(FlicDaemonBridgeHandler.java:70) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`

**Comment by pfink** [comment]
New version is prepared but not sufficiently tested yet. You may want to give it a shot and provide some feedback here. .jar is attached.

New feature: Scanning in PaperUI will now add all buttons that were verified by simpleclient at once.

Please note that the `pressed-switch` channel has been removed. [Profiles ](https://www.openhab.org/docs/configuration/items.html#profiles) are now the recommended way for configuration.

[attachment deleted]

**Comment by guyv** [comment]
I'm always getting "Configuration (hostname, port) is invalid and cannot be parsed."

Why should the rawPort be null here?
https://github.com/pfink/openhab2-flicbutton/blob/master/src/main/java/org/openhab/binding/flicbutton/handler/FlicDaemonBridgeConfiguration.java#L37

**Comment by karidavidsson** [comment]
When I start the openhab fresh the above reported error is no longer in the log. Unfortunatly it is not connecting to the flic button daemon. The PaperUI shows the flicd with state "Bridge-Unitialized".

If I refresh the thing configuration file for the flicd I get the following crashlog:
`2019-12-23 12:00:26.329 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.dispose()' on 'org.openhab.binding.flicbutton.handler.FlicButtonHandler@a40902': null
java.lang.NullPointerException: null
	at org.openhab.binding.flicbutton.handler.FlicButtonHandler.dispose(FlicButtonHandler.java:88) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-12-23 12:00:26.367 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while disposing handler of thing 'flicbutton:button:vinaminni:80-e4-da-74-c2-a6': null
java.lang.NullPointerException: null
	at org.openhab.binding.flicbutton.handler.FlicButtonHandler.dispose(FlicButtonHandler.java:88) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-12-23 12:00:26.419 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.dispose()' on 'org.openhab.binding.flicbutton.handler.FlicButtonHandler@857bb9': null
java.lang.NullPointerException: null
	at org.openhab.binding.flicbutton.handler.FlicButtonHandler.dispose(FlicButtonHandler.java:88) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-12-23 12:00:26.428 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while disposing handler of thing 'flicbutton:button:vinaminni:80-e4-da-74-c2-a9': null
java.lang.NullPointerException: null
	at org.openhab.binding.flicbutton.handler.FlicButtonHandler.dispose(FlicButtonHandler.java:88) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-12-23 12:00:26.477 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.dispose()' on 'org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler@17318dd': null
java.lang.NullPointerException: null
	at org.openhab.binding.flicbutton.internal.discovery.FlicSimpleclientDiscoveryServiceImpl.stopBackgroundDiscovery(FlicSimpleclientDiscoveryServiceImpl.java:119) ~[?:?]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.deactivate(AbstractDiscoveryService.java:426) ~[?:?]
	at org.openhab.binding.flicbutton.internal.discovery.FlicSimpleclientDiscoveryServiceImpl.deactivate(FlicSimpleclientDiscoveryServiceImpl.java:72) ~[?:?]
	at org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler.dispose(FlicDaemonBridgeHandler.java:139) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-12-23 12:00:26.543 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while disposing handler of thing 'flicbutton:flicd-bridge:vinaminni': null
java.lang.NullPointerException: null
	at org.openhab.binding.flicbutton.internal.discovery.FlicSimpleclientDiscoveryServiceImpl.stopBackgroundDiscovery(FlicSimpleclientDiscoveryServiceImpl.java:119) ~[?:?]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.deactivate(AbstractDiscoveryService.java:426) ~[?:?]
	at org.openhab.binding.flicbutton.internal.discovery.FlicSimpleclientDiscoveryServiceImpl.deactivate(FlicSimpleclientDiscoveryServiceImpl.java:72) ~[?:?]
	at org.openhab.binding.flicbutton.handler.FlicDaemonBridgeHandler.dispose(FlicDaemonBridgeHandler.java:139) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-12-23 12:00:26.568 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'Runnable.run()' on 'org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$$Lambda$554/33239@d00ae9': null
java.lang.NullPointerException: null
	at org.openhab.binding.flicbutton.internal.discovery.FlicSimpleclientDiscoveryServiceImpl.stopBackgroundDiscovery(FlicSimpleclientDiscoveryServiceImpl.java:119) ~[?:?]
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.deactivate(AbstractDiscoveryService.java:426) ~[?:?]
	at org.openhab.binding.flicbutton.internal.discovery.FlicSimpleclientDiscoveryServiceImpl.deactivate(FlicSimpleclientDiscoveryServiceImpl.java:72) ~[?:?]
	at org.openhab.binding.flicbutton.internal.FlicButtonHandlerFactory.unregisterDiscoveryService(FlicButtonHandlerFactory.java:98) ~[?:?]
	at org.openhab.binding.flicbutton.internal.FlicButtonHandlerFactory.removeHandler(FlicButtonHandlerFactory.java:81) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.unregisterHandler(BaseThingHandlerFactory.java:248) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl.lambda$5(ThingManagerImpl.java:794) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`
And the flicd thing dissapears from the Configuration->Thing list in the PaperUI.
I have verified that tthe simpleclient is able to connect and get the flic button presses.
The controller has upgraded to 2.5.0 release of openhab.

**Comment by pfink** [comment]
Weird that this didn't occur on my tests. I can only explain that something failed during deployment and I actually tested an older build. This build should be better, I fixed [this](https://github.com/pfink/openhab2-flicbutton/blob/master/src/main/java/org/openhab/binding/flicbutton/handler/FlicDaemonBridgeConfiguration.java#L37), now thanks!
[org.openhab.binding.flicbutton-1.0.0-SNAPSHOT.zip](https://github.com/pfink/openhab2-flicbutton/files/3995193/org.openhab.binding.flicbutton-1.0.0-SNAPSHOT.zip)

**Comment by karidavidsson** [comment]
I am not sure how, but the karaf console listed two instances of the jar file.
I cleaned up the addons folder and uninstalled with the bundle:uninstall command on the karaf console and and then reinstalled the jar file into the addons folder (after shutdown).
Now the flic button bridge is initialized and the butten events are deliverd as before.

Is it maybe not enough to copy the new jar file to the addons folder and remove the old jar file as the instructions instruct?

This is with org.openhab.binding.flicbutton-1.0.0-SNAPSHOT.zip.

**Comment by pfink** [comment]
> Is it maybe not enough to copy the new jar file to the addons folder and remove the old jar file as the instructions instruct?

I don't know, never trust OSGi 🗡 I have the impression sometimes hot deployment is enough, sometimes restart is needed and sometimes even `bundle:uninstall` - independently whether it's a different version or not.

**Comment by guyv** [comment]
this version is working for me, thx for the swift response

**Comment by martonsz85** [comment]
I'm glad I found this issue, it works with OH 2.5.0 for me, too. Thanks for the quick fix. Any plans on a new release?

**Comment by pfink** [comment]
Release is available now: https://github.com/pfink/openhab2-flicbutton/releases/tag/1.0.0

Please consider the upgrade notes, there are some changes that need your attention.
